-- F1 Live Pulse MVP Schema

-- 1. Session State (Singleton pro udržování stavu závodu a počasí)
CREATE TABLE public.session_state (
    id int PRIMARY KEY DEFAULT 1,
    flag varchar(20) NOT NULL DEFAULT 'Green',
    remaining_time varchar(20),
    remaining_laps int,
    track_temp numeric(5, 2),
    air_temp numeric(5, 2),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ujistíme se, že tam vždy je aspoň 1 record
INSERT INTO public.session_state (id, flag) VALUES (1, 'Green') ON CONFLICT DO NOTHING;

-- 2. Leaderboard (Aktuální pozice na trati, updatuje se pořád)
CREATE TABLE public.leaderboard (
    driver_number varchar(10) PRIMARY KEY,
    position int NOT NULL,
    broadcast_name varchar(5) NOT NULL,
    team_color varchar(7) NOT NULL,
    gap_to_leader varchar(20),
    interval varchar(20),
    compound varchar(5),
    tyre_age int,
    in_pit boolean DEFAULT false,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Telemetrie (Pouze pro sledované jezdce, masivní insert rate)
CREATE TABLE public.telemetry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_number varchar(10) NOT NULL,
    session_time numeric(10, 3) NOT NULL, -- Časový offset od startu session pro správné seřazení spíše než absolutní čas
    speed int NOT NULL,
    rpm int NOT NULL,
    gear int NOT NULL,
    throttle int NOT NULL,
    brake int NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index pro rychlé hledání telemetrie podle jezdce a session time
CREATE INDEX idx_telemetry_driver_time ON public.telemetry (driver_number, session_time DESC);

-- Zapnutí Supabase Realtime Brodcast a CDC pro tyto tabulky
ALTER PUBLICATION supabase_realtime ADD TABLE public.session_state;
ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
-- Telemetry data budeme insertovat a zároveň mohou jít přes insert CDC eventy, 
-- Nicméně u 60fps dat možná bude lepší použít Broadcast channel přímo v Pythonu a DB používat jako histori.
-- Zapneme ale Realtime CDC pro jistotu na vše
ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry;
